[package]
name = "drm"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
repository = "https://github.com/Smithay/drm-rs"
version = "0.3.3"
license = "MIT"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]

[dependencies]
drm-sys = { git = "https://github.com/kosyak/drm-rs", branch = "master" }
nix = "0.8.1"
derive_more = "0.7.1"

[dependencies.error-chain]
version = "0.11.0"
default-features = false

[features]
default = ["use_bindgen"]
use_bindgen = ["drm-sys/use_bindgen"]
